# Generated by Django 5.2.4 on 2026-02-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('professional', 'Professional'), ('academic', 'Academic'), ('personal', 'Personal'), ('engineering', 'Engineering')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='Temporary short description', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma separated values (e.g. Django, React, PostgreSQL)', max_length=255),
        ),
    ]
