# Generated by Django 5.2.4 on 2026-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_video_url',
            field=models.URLField(blank=True),
        ),
    ]
