services:
  - type: web
    name: josenoet
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn JosePortafolio.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "josenoet.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://josenoet.onrender.com"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "jmnt2012@gmail.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.5"
    plan: free
