# Generated by Django 5.2.4 on 2026-06-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='jmnt2012@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='+56 9 30387145', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='Backend Developer', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='professional_title',
            field=models.CharField(blank=True, default='Backend Engineer', max_length=180),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Jose Noe', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='+56930387145', max_length=30),
        ),
    ]
