# Generated by Django 5.2.4 on 2026-08-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('projects', '0004_project_demo_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('github_click', 'GitHub click'), ('demo_click', 'Demo click'), ('contact_click', 'Contact click'), ('email_click', 'Email click'), ('phone_click', 'Phone click'), ('linkedin_click', 'LinkedIn click'), ('cv_download', 'CV download'), ('contact_submit', 'Contact submit')], db_index=True, max_length=50)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('ip_hash', models.CharField(max_length=64)),
                ('user_agent_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
