# Generated by Django 5.2.4 on 2026-08-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='session_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='visitor_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='session_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='visitor_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='projectview',
            name='session_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='projectview',
            name='visitor_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
