# Generated by Django 5.2.4 on 2026-08-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_analyticsevent_session_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('github_click', 'GitHub click'), ('demo_click', 'Demo click'), ('contact_click', 'Contact click'), ('email_click', 'Email click'), ('phone_click', 'Phone click'), ('linkedin_click', 'LinkedIn click'), ('whatsapp_click', 'WhatsApp click'), ('cv_download', 'CV download'), ('contact_submit', 'Contact submit')], db_index=True, max_length=50),
        ),
    ]
